version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 25
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist/angular-aws-test/browser
  discard-paths: no
