version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 25
    commands:
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no
